apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    app: komodor
  name: komodor-critical-pods
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end}}
spec:
  hard:
    pods: 2
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values:
          - system-cluster-critical
