annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Komodor Agent
  catalog.cattle.io/release-name: komodor-agent
apiVersion: v1
appVersion: 0.1.99
description: Watches and send kubernetes resource-related events
icon: https://partner-charts.rancher.io/assets/logos/komodor.png
kubeVersion: 1.16-0 - 1.21-0
name: k8s-watcher
version: 0.10.1101
