annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Kubeslice-Controller
  catalog.cattle.io/release-name: kubeslice-controller
apiVersion: v2
appVersion: 0.1.1
description: A Helm chart for kubeslice-controller
kubeVersion: 1.21 - 1.24
name: kubeslice-controller
type: application
version: 0.1.1
