annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Minio Operator
  catalog.cattle.io/release-name: minio-operator
apiVersion: v2
appVersion: v4.4.17
description: A Helm chart for MinIO Operator
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
keywords:
- storage
- object-storage
- S3
kubeVersion: '>=1.19.0-0'
maintainers:
- email: dev@minio.io
  name: MinIO, Inc
name: minio-operator
sources:
- https://github.com/minio/operator
type: application
version: 4.4.1700
