---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "4"
  creationTimestamp: null
  name: speedscale-operator-pre-install
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 0
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - args:
        - |-
          speedctl init --overwrite --no-rcfile-update \
          --api-key {{ required "A valid .Values.apiKey is required!" .Values.apiKey }} \
          --app-url {{ required "A valid .Values.appUrl is required!" .Values.appUrl }}
        command:
        - sh
        - -c
        image: '{{ .Values.image.registry }}/speedscale-cli:{{ .Values.image.tag }}'
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: speedscale-cli
        resources: {}
      restartPolicy: Never
status: {}
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "1"
  creationTimestamp: null
  labels:
    app: speedscale-operator
    controlplane.speedscale.com/component: operator
  name: speedscale-operator-provisioning
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "2"
  creationTimestamp: null
  name: speedscale-operator-provisioning
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "3"
  creationTimestamp: null
  name: speedscale-operator-provisioning
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: speedscale-operator-provisioning
subjects:
- kind: ServiceAccount
  name: speedscale-operator-provisioning
  namespace: {{ .Release.Namespace }}
